title: Lina Breslav's Portfolio
url: "https://linabreslav.github.io/portfolioreal/" # the base hostname & protocol for your site
twitter_username: linabreslav
github_username:  linabreslav

# Build settings
markdown: kramdown
